### ISSUE TITLE
Windows 10: `FileNotFoundError: [WinError 2] The system cannot find the file specified`

### ISSUE THREAD

**Issue by zsarnett** [jquesnelle/txt2imghd#27]
```
Traceback (most recent call last):
  File "scripts/txt2imghd.py", line 549, in <module>
    main()
  File "scripts/txt2imghd.py", line 365, in main
    text2img2(opt)
  File "scripts/txt2imghd.py", line 476, in text2img2
    realesrgan2x(opt.realesrgan, os.path.join(sample_path, f"{base_filename}.png"), os.path.join(sample_path, f"{base_filename}u.png"))
  File "scripts/txt2imghd.py", line 368, in realesrgan2x
    process = subprocess.Popen([
  File "C:\Users\user\miniconda3\envs\ldm\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\miniconda3\envs\ldm\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Seeing this error after the txt2img function runs and then trys to run the realesrgan2x sub process

I have added the executables and bin files to my root folder, models folder, even the scripts folder

**Comment by zsarnett** [comment]
... I am usually on a mac. Downloaded the incorrect files 😅
