### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'personalization_config'

### ISSUE THREAD

**Issue by benedlore** [jquesnelle/txt2imghd#31]
I also ran into the `ImportError: cannot import name 'WatermarkEncoder' from 'imWatermark'`  error, and then ran `pip install invisible-watermark` to resolve that.

Directly after that, though, I run into this error, though, and I am not smart enough to understand how to get around it:

```
Traceback (most recent call last):
  File "scripts/txt2imghd.py", line 550, in <module>
    main()
  File "scripts/txt2imghd.py", line 365, in main
    text2img2(opt)
  File "scripts/txt2imghd.py", line 388, in text2img2
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2imghd.py", line 53, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "d:\dropbox\projects\machinelearning\imagegeneration\stablediffusion\sourcelstein\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
TypeError: __init__() missing 1 required positional argument: 'personalization_config'
```

**Comment by benedlore** [comment]
Not sure how it happened, but something else somehow went wrong, updating my environment again fixedi though

`conda env update --file environment.yaml`
